### ISSUE TITLE
[Bug] Crash after opening any file.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [damionx7/Zettel-Notes-Documentation#44]
I can open files, and they render for a split second, but Zettel Notes immediately crashes afterward.

**Comment by damionx7** [comment]
Please share more details including the note file and if possible logs of the crash.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/damionx7/Zettel-Notes-Documentation/issues/44#issuecomment-1902069196

It crashes when loading *any* file, so just clone https://gitlab.com/rokejulianlockhart/rokejulianlockhart.git (and https://gitlab.com/rokejulianlockhart/s4a3h4/ if that doesn't work, but you won't have access to it unless necessary).

**Comment by damionx7** [comment]
I have fixed this bug. It should be live in the next update.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/damionx7/Zettel-Notes-Documentation/issues/44#issuecomment-1903011720

@damionx7, unfortunately, although I'm using version 2.4.5, this bug remains. However, I have identified that the cause must be certain UTF-8 characters in the filename:

> https://github.com/damionx7/Zettel-Notes-Documentation/assets/42837531/5e9c02d4-ea23-43f4-9d77-cee34b073a78

For instance, take:

```.MD
<!-- to be added when on a desktop pc, gimme a moment -->
```

...which, notably, is converted by Zettel in the filename modification window to:

```.MD
__title_ _Bitwarden Note Template_,_id_ _s4zw11____.JSON5_.txt.MD
```

**Comment by damionx7** [comment]
Please try latest version 2.4.6. This should fix it.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/damionx7/Zettel-Notes-Documentation/issues/44#issuecomment-1908410073

@damionx7, that worked. Apologies - it seems Google Play is offering me updates a day late (I received 2.4.5 yesterday, and 2.4.6 today). I forget CI takes time.
